package com.github.seijuro.publicdata;

public enum PublicDataAPIServices {
    NPS_BUSINESS_PLACE_NORMAL,
    NPS_BUSINESS_PLACE_DETAIL,
    NPS_STATS,

    SPEC_CONSTRUCT,
    SPEC_FOREIGNCAPITAL,
    SPEC_PRODUCT,
    SPEC_SERVICE,

    RECALL,
    RECALL_PAGEABLE,

    INSURANCE,

    THE_USE_OF_ELECTROCITY,
    THE_USE_OF_GAS,

    PYRAMID_SELLING,
    PYRAMID_SELLING_DEATIL,

    TELE_MARKETING_SELLER,
    COLD_CALLING_SELLER,
    DOOR_TO_DOOR_SEELER;
}
